### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by make-github-pseudonymous-again**
- Add LICENSE of forked project
  - Add GitHub workflow to run test suite on pushes and PRs
  - Fix some bugs
  - Upgrade all dependencies
  - Clean up source
  - Remove empty test suites

### CODE REVIEW

**Comment by make-github-pseudonymous-again** [comment]
@zodern I need a new release of `@zodern/nodemiral` based on these changes to be used by `meteor-up`. I am happy to help. Just tell me if it is possible, and what needs to be done in order to make it happen.

**Comment by zodern** [comment]
Thanks @make-github-pseudonymous-again, this looks really good. The only concern I have is updating ejs to version 3 will be a breaking change for Meteor Up since it removes filters (plugins and hooks could possibly have ejs templates that use filters). I've been waiting for Meteor Up 2, which will probably be the next version after 1.6, before updating ejs. 

Are you wanting to use features in new version of ejs, or is this to fix the vulnerability in old versions of ejs?

**Comment by make-github-pseudonymous-again** [comment]
Hi @zodern! I just want those vulnerability warnings gone. Nothing rational about it. Although in one of my projects it would allow renovate dependency upgrades to be automatically merged in, which is currently not possible with the vulnerabilities being flagged on each PR. I have not tried anything to work around it.

While writing this PR I read about legacy `ejs` vulnerabilities and at least one of them is worrying. For instance unsanitized filenames could lead to arbitrary code execution. No idea how serious these are in the use-case of meteor-up.

`ejs` 0.8.x is really old, same thing for other dependencies of `nodemiral`. I am also worried these are so old nobody today would be bothered to check for security risks.

It would be good I think if all these dependencies were updated. We can discuss how to fix the missing features of recent `ejs` if you want to.

**Comment by zodern** [comment]
Thanks @make-github-pseudonymous-again. I will merge this, then downgrade ejs to 2.x, and replace ssh2 with ssh2-classic to minimize breaking changes while keeping the security fixes. Once I start on Meteor Up 2 I will fully upgrade ejs and ssh2.

**Pull request merged**
